### ISSUE TITLE
Example of service definition is not follow actual template

### ISSUE THREAD

**Issue by gollariel** [d7561985/k8app#16]
Inside values.yaml we have the next definition of service:
```
services:
  enabled: false
  spec: {}
    #  test-api-sv:
    #    name: test-api
    #    http:
    #      protocol: TCP
    #      externalPort: 80
    #      internalPort: 8000
```

So, we expect to have multiple service defined per project, but service.yaml does not use a spec at all:
```
{{- if .Values.service.enabled -}}
{{- $serviceDefaultName :=  printf "%s-%s" (include "name" .) "sv" -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ $serviceDefaultName }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  ports:
{{- range $key, $value := .Values.service.ports }}
  - port: {{ default 80 $value.externalPort }}
    targetPort: {{ $value.internalPort }}
    protocol: {{ $value.protocol }}
    name: {{ $key }}
{{- end }}
  selector:
    app: {{ template "name" . }}
    release: "{{ .Release.Name }}"
  type: "ClusterIP"
{{- end -}}
```
